export const DEVELOPMENT_SERVER = 'http://localhost:5000/api/v1';
export const PRODUCTION_HEROKU_SERVER = 'https://darkdocs-shop.herokuapp.com/api/v1';
export const DARKDOCS_SHOP_ADMIN_USER_KEY = 'DARKDOCS_SHOP_ADMIN_USER_KEY';
export const DARKDOCS_SHOP_ADMIN_TOKEN_KEY = 'DARKDOCS_SHOP_ADMIN_TOKEN_KEY';
export const DARKDOCS_SHOP_ADMIN_ORDERS_KEY = 'DARKDOCS_SHOP_ADMIN_ORDERS_KEY';
